name: CI

on:
  pull_request:

jobs:
  pest-tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Pest Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: secret
        run: ./vendor/bin/pest

  lint-check:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'
          php-extensions: 'json, dom, curl, libxml, mbstring'

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Pint Check
        run: ./vendor/bin/pint --test
