name: Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

  release:
    types:
      - published

jobs:
  deploy:
    if: github.event_name == 'release' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push')

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment: ${{ github.event_name == 'workflow_run' && 'staging' || 'production' }}

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v7.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy to Server
        env:
          DEPLOY_URL: ${{vars.DEPLOY_URL}}
        run: echo ${{ env.DEPLOY_URL }}
