name: Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

  release:
    types:
      - published

jobs:
  deploy:
    if: github.event_name == 'release' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push')

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment: ${{ github.event_name == 'workflow_run' && 'staging' || 'production' }}

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v7.0.0

      - name: Deploy to Server
        env:
          DEPLOY_URL: ${{vars.DEPLOY_URL}}
        run: echo ${{ env.DEPLOY_URL }}
