name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  run-laravel-pint:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v7.0.0

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'
          extensions: 'json, dom, curl, libxml, mbstring'

      - name: Install Laravel Pint
        run: composer require laravel/pint

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Push Changes Back to Repository
        run: |
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ env.GIT_USERNAME }}
          git add .
          git commit -m "Pint Fixes" || exit 0
          git push
