name: Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v7.0.0

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.37.2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, memcached, gmp, :php-psr
          tools: composer:v2

      - name: Cache Dependencies
        uses: actions/cache@v6.1.0
        with:
          key: cache-dependencies-${{ hashFiles('**/composer.lock') }}
          path: vendor

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: password
        run: ./vendor/bin/pest
