name: Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306

    env:
      PHP_VERSION: 8.4
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, memcached, gmp, :php-psr

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v7.0.0

      - name: Setup PHP Extensions Cache Environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          key: cache-extensions-v1

      - name: Cache PHP Extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.37.2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v6.1.0
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: cache-dependencies-${{ hashFiles('**/composer.lock') }}
          restore-keys: cache-dependencies-

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: secret
        run: ./vendor/bin/pest
